# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/banana.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/bareland.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/carrot.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/corn.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/dragonfruit.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/garlic.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/guava.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/inundated.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/md5sum.txt
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/peanut.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/pineapple.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/pumpkin.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/rice.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/soybean.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/sugarcane.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/train/tomato.zip

# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/md5sum.txt
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/submission_example.csv
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_0.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_1.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_2.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_3.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_4.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_5.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_6.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_7.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_8.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_9.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_a.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_b.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_c.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_d.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_e.zip
# wget http://aicup-dataset.aidea-web.tw:18080/dataset/test/test_f.zip
